// path: prisma/seed.ts
import { PrismaClient } from "@prisma/client";
const prisma = new PrismaClient();

type FoodInput = {
  name: string;
  unit: string;
  calories: number;
  protein: number;
  carbs: number;
  fat: number;
};

const FOODS: FoodInput[] = [
  {
    name: "Boiled Rice",
    unit: "per_100g",
    calories: 130,
    protein: 2.7,
    carbs: 28,
    fat: 0.3,
  },
  {
    name: "Brown Rice (cooked)",
    unit: "per_100g",
    calories: 111,
    protein: 2.6,
    carbs: 23,
    fat: 0.9,
  },
  {
    name: "Chapati",
    unit: "per_piece",
    calories: 120,
    protein: 3.1,
    carbs: 18,
    fat: 3.2,
  },
  {
    name: "Phulka",
    unit: "per_piece",
    calories: 90,
    protein: 2.5,
    carbs: 16,
    fat: 1.2,
  },
  {
    name: "Paratha (plain)",
    unit: "per_piece",
    calories: 170,
    protein: 3.5,
    carbs: 22,
    fat: 7,
  },
  {
    name: "Idli",
    unit: "per_piece",
    calories: 58,
    protein: 2,
    carbs: 12,
    fat: 0.4,
  },
  {
    name: "Dosa (plain)",
    unit: "per_100g",
    calories: 184,
    protein: 3.9,
    carbs: 30,
    fat: 5.4,
  },
  {
    name: "Uttapam (plain)",
    unit: "per_100g",
    calories: 210,
    protein: 5,
    carbs: 35,
    fat: 5,
  },
  {
    name: "Pongal (ven)",
    unit: "per_100g",
    calories: 150,
    protein: 4,
    carbs: 22,
    fat: 4,
  },
  {
    name: "Upma",
    unit: "per_100g",
    calories: 135,
    protein: 3.5,
    carbs: 23,
    fat: 3,
  },
  {
    name: "Poha",
    unit: "per_100g",
    calories: 130,
    protein: 2.7,
    carbs: 25,
    fat: 2.5,
  },
  {
    name: "Sambar",
    unit: "per_100g",
    calories: 55,
    protein: 3,
    carbs: 8,
    fat: 1,
  },
  {
    name: "Rasam",
    unit: "per_100g",
    calories: 25,
    protein: 1,
    carbs: 4,
    fat: 0.5,
  },
  {
    name: "Dal (Lentil Curry)",
    unit: "per_100g",
    calories: 118,
    protein: 7.6,
    carbs: 18,
    fat: 1.5,
  },
  {
    name: "Chana Masala",
    unit: "per_100g",
    calories: 180,
    protein: 9,
    carbs: 27,
    fat: 4,
  },
  {
    name: "Rajma (Kidney Bean Curry)",
    unit: "per_100g",
    calories: 150,
    protein: 8,
    carbs: 25,
    fat: 2,
  },
  {
    name: "Chole (Chickpea Curry)",
    unit: "per_100g",
    calories: 180,
    protein: 9,
    carbs: 27,
    fat: 4,
  },
  {
    name: "Paneer (raw)",
    unit: "per_100g",
    calories: 265,
    protein: 18,
    carbs: 6,
    fat: 20,
  },
  {
    name: "Paneer Tikka (grilled)",
    unit: "per_100g",
    calories: 270,
    protein: 22,
    carbs: 6,
    fat: 18,
  },
  {
    name: "Tofu (firm)",
    unit: "per_100g",
    calories: 76,
    protein: 8,
    carbs: 2,
    fat: 4.8,
  },
  {
    name: "Curd (Dahi)",
    unit: "per_100g",
    calories: 61,
    protein: 3.5,
    carbs: 4.7,
    fat: 3.3,
  },
  {
    name: "Greek Yogurt (plain)",
    unit: "per_100g",
    calories: 97,
    protein: 10,
    carbs: 3.6,
    fat: 5,
  },
  {
    name: "Milk (toned)",
    unit: "per_100g",
    calories: 62,
    protein: 3.2,
    carbs: 5,
    fat: 3.5,
  },
  {
    name: "Buttermilk",
    unit: "per_100g",
    calories: 40,
    protein: 3,
    carbs: 4,
    fat: 1.5,
  },
  { name: "Ghee", unit: "per_5g", calories: 45, protein: 0, carbs: 0, fat: 5 },
  {
    name: "Vegetable Oil",
    unit: "per_5g",
    calories: 45,
    protein: 0,
    carbs: 0,
    fat: 5,
  },
  {
    name: "Chicken Breast (cooked)",
    unit: "per_100g",
    calories: 165,
    protein: 31,
    carbs: 0,
    fat: 3.6,
  },
  {
    name: "Chicken Curry (home-style)",
    unit: "per_100g",
    calories: 190,
    protein: 16,
    carbs: 4,
    fat: 12,
  },
  {
    name: "Mutton (cooked)",
    unit: "per_100g",
    calories: 250,
    protein: 26,
    carbs: 0,
    fat: 17,
  },
  {
    name: "Mutton Curry",
    unit: "per_100g",
    calories: 240,
    protein: 20,
    carbs: 3,
    fat: 16,
  },
  {
    name: "Egg (boiled)",
    unit: "per_piece",
    calories: 78,
    protein: 6.3,
    carbs: 0.6,
    fat: 5.3,
  },
  {
    name: "Egg White",
    unit: "per_piece",
    calories: 17,
    protein: 3.6,
    carbs: 0.2,
    fat: 0.1,
  },
  {
    name: "Fish (Rohu, cooked)",
    unit: "per_100g",
    calories: 150,
    protein: 26,
    carbs: 0,
    fat: 5,
  },
  {
    name: "Fish Fry (home-style)",
    unit: "per_100g",
    calories: 220,
    protein: 22,
    carbs: 5,
    fat: 12,
  },
  {
    name: "Prawns (cooked)",
    unit: "per_100g",
    calories: 99,
    protein: 24,
    carbs: 0,
    fat: 0.3,
  },
  {
    name: "Peanut Chutney",
    unit: "per_30g",
    calories: 170,
    protein: 6,
    carbs: 5,
    fat: 14,
  },
  {
    name: "Coconut Chutney",
    unit: "per_30g",
    calories: 120,
    protein: 2,
    carbs: 4,
    fat: 11,
  },
  {
    name: "Tomato Chutney",
    unit: "per_30g",
    calories: 25,
    protein: 1,
    carbs: 5,
    fat: 0.5,
  },
  {
    name: "Pickle (Achar)",
    unit: "per_15g",
    calories: 25,
    protein: 0.3,
    carbs: 1,
    fat: 2,
  },
  {
    name: "Mixed Veg Curry",
    unit: "per_100g",
    calories: 90,
    protein: 3,
    carbs: 12,
    fat: 3,
  },
  {
    name: "Aloo Curry (dry)",
    unit: "per_100g",
    calories: 130,
    protein: 2.5,
    carbs: 20,
    fat: 4,
  },
  {
    name: "Bhindi Masala",
    unit: "per_100g",
    calories: 110,
    protein: 3,
    carbs: 13,
    fat: 6,
  },
  {
    name: "Baingan Bharta",
    unit: "per_100g",
    calories: 120,
    protein: 3,
    carbs: 10,
    fat: 7,
  },
  {
    name: "Cabbage Stir-fry",
    unit: "per_100g",
    calories: 80,
    protein: 2,
    carbs: 10,
    fat: 3,
  },
  {
    name: "Palak Paneer",
    unit: "per_100g",
    calories: 180,
    protein: 10,
    carbs: 8,
    fat: 12,
  },
  {
    name: "Methi Dal",
    unit: "per_100g",
    calories: 120,
    protein: 7,
    carbs: 18,
    fat: 2,
  },
  {
    name: "Kadhi",
    unit: "per_100g",
    calories: 95,
    protein: 4,
    carbs: 9,
    fat: 5,
  },
  {
    name: "Curd Rice",
    unit: "per_100g",
    calories: 130,
    protein: 3.5,
    carbs: 20,
    fat: 3,
  },
  {
    name: "Lemon Rice",
    unit: "per_100g",
    calories: 175,
    protein: 3,
    carbs: 28,
    fat: 6,
  },
  {
    name: "Fried Rice (veg)",
    unit: "per_100g",
    calories: 180,
    protein: 4,
    carbs: 28,
    fat: 6,
  },
  {
    name: "Biryani (chicken)",
    unit: "per_100g",
    calories: 210,
    protein: 9,
    carbs: 28,
    fat: 7,
  },
  {
    name: "Biryani (veg)",
    unit: "per_100g",
    calories: 190,
    protein: 4,
    carbs: 30,
    fat: 6,
  },
  {
    name: "Pulao (veg)",
    unit: "per_100g",
    calories: 170,
    protein: 3.5,
    carbs: 28,
    fat: 4,
  },
  {
    name: "Khichdi (moong dal)",
    unit: "per_100g",
    calories: 120,
    protein: 4,
    carbs: 22,
    fat: 2,
  },
  {
    name: "Dhokla",
    unit: "per_100g",
    calories: 160,
    protein: 6,
    carbs: 24,
    fat: 5,
  },
  {
    name: "Thepla",
    unit: "per_piece",
    calories: 120,
    protein: 3,
    carbs: 17,
    fat: 4,
  },
  {
    name: "Pav (bun)",
    unit: "per_piece",
    calories: 150,
    protein: 4,
    carbs: 28,
    fat: 1.5,
  },
  {
    name: "Pav Bhaji",
    unit: "per_100g",
    calories: 140,
    protein: 3,
    carbs: 20,
    fat: 5,
  },
  {
    name: "Idiyappam",
    unit: "per_100g",
    calories: 150,
    protein: 2,
    carbs: 33,
    fat: 0.5,
  },
  {
    name: "Appam",
    unit: "per_piece",
    calories: 85,
    protein: 1.5,
    carbs: 17,
    fat: 1,
  },
  {
    name: "Pesarattu",
    unit: "per_100g",
    calories: 170,
    protein: 8,
    carbs: 25,
    fat: 4,
  },
  {
    name: "Medu Vada",
    unit: "per_piece",
    calories: 97,
    protein: 2,
    carbs: 7,
    fat: 6,
  },
  {
    name: "Samosa (veg)",
    unit: "per_piece",
    calories: 180,
    protein: 4,
    carbs: 20,
    fat: 9,
  },
  {
    name: "Kheer (rice pudding)",
    unit: "per_100g",
    calories: 145,
    protein: 4,
    carbs: 22,
    fat: 4,
  },
  {
    name: "Halwa (suji)",
    unit: "per_100g",
    calories: 200,
    protein: 3,
    carbs: 35,
    fat: 6,
  },
  {
    name: "Gulab Jamun",
    unit: "per_piece",
    calories: 150,
    protein: 2,
    carbs: 20,
    fat: 7,
  },
  {
    name: "Jalebi",
    unit: "per_25g",
    calories: 100,
    protein: 0.5,
    carbs: 20,
    fat: 2,
  },
  {
    name: "Banana",
    unit: "per_piece",
    calories: 105,
    protein: 1.3,
    carbs: 27,
    fat: 0.3,
  },
  {
    name: "Apple",
    unit: "per_100g",
    calories: 52,
    protein: 0.3,
    carbs: 14,
    fat: 0.2,
  },
  {
    name: "Orange",
    unit: "per_100g",
    calories: 47,
    protein: 0.9,
    carbs: 12,
    fat: 0.1,
  },
  {
    name: "Mango",
    unit: "per_100g",
    calories: 60,
    protein: 0.8,
    carbs: 15,
    fat: 0.4,
  },
  {
    name: "Papaya",
    unit: "per_100g",
    calories: 43,
    protein: 0.5,
    carbs: 11,
    fat: 0.3,
  },
  {
    name: "Pomegranate",
    unit: "per_100g",
    calories: 83,
    protein: 1.7,
    carbs: 19,
    fat: 1.2,
  },
  {
    name: "Grapes",
    unit: "per_100g",
    calories: 69,
    protein: 0.7,
    carbs: 18,
    fat: 0.2,
  },
  {
    name: "Dates (dried)",
    unit: "per_20g",
    calories: 56,
    protein: 0.5,
    carbs: 15,
    fat: 0,
  },
  {
    name: "Almonds",
    unit: "per_28g",
    calories: 164,
    protein: 6,
    carbs: 6,
    fat: 14,
  },
  {
    name: "Peanuts (roasted)",
    unit: "per_28g",
    calories: 166,
    protein: 7,
    carbs: 6,
    fat: 14,
  },
  {
    name: "Cashews",
    unit: "per_28g",
    calories: 157,
    protein: 5,
    carbs: 9,
    fat: 12,
  },
  {
    name: "Walnuts",
    unit: "per_28g",
    calories: 185,
    protein: 4,
    carbs: 4,
    fat: 18,
  },
  {
    name: "Chia Seeds",
    unit: "per_20g",
    calories: 97,
    protein: 3,
    carbs: 8,
    fat: 6,
  },
  {
    name: "Flax Seeds",
    unit: "per_20g",
    calories: 110,
    protein: 3.8,
    carbs: 6,
    fat: 8.5,
  },
  {
    name: "Oats (dry)",
    unit: "per_40g",
    calories: 154,
    protein: 6,
    carbs: 27,
    fat: 3,
  },
  {
    name: "Cornflakes",
    unit: "per_30g",
    calories: 114,
    protein: 2,
    carbs: 25,
    fat: 0.2,
  },
  {
    name: "Bread (white)",
    unit: "per_slice",
    calories: 70,
    protein: 2.3,
    carbs: 12,
    fat: 1,
  },
  {
    name: "Bread (brown)",
    unit: "per_slice",
    calories: 68,
    protein: 3,
    carbs: 11.5,
    fat: 1,
  },
  {
    name: "Peanut Butter",
    unit: "per_15g",
    calories: 90,
    protein: 3.5,
    carbs: 3,
    fat: 8,
  },
  { name: "Jam", unit: "per_15g", calories: 40, protein: 0, carbs: 10, fat: 0 },
  { name: "Sugar", unit: "per_5g", calories: 20, protein: 0, carbs: 5, fat: 0 },
  {
    name: "Honey",
    unit: "per_10g",
    calories: 30,
    protein: 0,
    carbs: 8,
    fat: 0,
  },
  {
    name: "Tea (with milk+ sugar)",
    unit: "per_200ml",
    calories: 120,
    protein: 3,
    carbs: 20,
    fat: 3,
  },
  {
    name: "Coffee (with milk)",
    unit: "per_200ml",
    calories: 80,
    protein: 3,
    carbs: 8,
    fat: 3,
  },
  {
    name: "Lassi (sweet)",
    unit: "per_200ml",
    calories: 260,
    protein: 9,
    carbs: 36,
    fat: 8,
  },
  {
    name: "Coconut Water",
    unit: "per_200ml",
    calories: 38,
    protein: 0.7,
    carbs: 9,
    fat: 0.2,
  },
  {
    name: "Lemon Water (no sugar)",
    unit: "per_200ml",
    calories: 5,
    protein: 0,
    carbs: 1,
    fat: 0,
  },
  {
    name: "Ragi Mudde",
    unit: "per_100g",
    calories: 110,
    protein: 2.7,
    carbs: 23,
    fat: 0.8,
  },
  {
    name: "Ragi Dosa",
    unit: "per_100g",
    calories: 170,
    protein: 4,
    carbs: 28,
    fat: 3,
  },
  {
    name: "Bajra Roti",
    unit: "per_piece",
    calories: 120,
    protein: 3.5,
    carbs: 22,
    fat: 1.5,
  },
  {
    name: "Jowar Roti",
    unit: "per_piece",
    calories: 110,
    protein: 2.8,
    carbs: 23,
    fat: 1,
  },
  {
    name: "Multigrain Roti",
    unit: "per_piece",
    calories: 120,
    protein: 3.2,
    carbs: 20,
    fat: 2,
  },
  {
    name: "Sprouts Salad",
    unit: "per_100g",
    calories: 90,
    protein: 6,
    carbs: 16,
    fat: 1,
  },
  {
    name: "Green Salad",
    unit: "per_100g",
    calories: 25,
    protein: 1.3,
    carbs: 5,
    fat: 0.2,
  },
  {
    name: "Fruit Salad",
    unit: "per_100g",
    calories: 70,
    protein: 0.7,
    carbs: 17,
    fat: 0.2,
  },
  {
    name: "Chicken Tikka",
    unit: "per_100g",
    calories: 195,
    protein: 27,
    carbs: 3,
    fat: 8,
  },
  {
    name: "Tandoori Chicken",
    unit: "per_100g",
    calories: 215,
    protein: 26,
    carbs: 3,
    fat: 10,
  },
  {
    name: "Fish Curry",
    unit: "per_100g",
    calories: 160,
    protein: 15,
    carbs: 4,
    fat: 9,
  },
  {
    name: "Curd (low-fat)",
    unit: "per_100g",
    calories: 55,
    protein: 3.8,
    carbs: 4.5,
    fat: 1.5,
  },
  {
    name: "Paneer Bhurji",
    unit: "per_100g",
    calories: 210,
    protein: 14,
    carbs: 8,
    fat: 14,
  },
  {
    name: "Masala Omelette",
    unit: "per_100g",
    calories: 154,
    protein: 11,
    carbs: 2,
    fat: 11,
  },
  {
    name: "Dal Khichdi (veg)",
    unit: "per_100g",
    calories: 130,
    protein: 4,
    carbs: 23,
    fat: 2,
  },
  {
    name: "Chicken Soup",
    unit: "per_200ml",
    calories: 120,
    protein: 10,
    carbs: 4,
    fat: 6,
  },
  {
    name: "Veg Soup",
    unit: "per_200ml",
    calories: 70,
    protein: 2,
    carbs: 12,
    fat: 1,
  },
  {
    name: "Idli Sambar (1 idli+ sambar)",
    unit: "per_set",
    calories: 110,
    protein: 4,
    carbs: 17,
    fat: 2,
  },
  {
    name: "Dosa with Chutney",
    unit: "per_100g",
    calories: 220,
    protein: 4,
    carbs: 32,
    fat: 8,
  },
  {
    name: "Puri (fried)",
    unit: "per_piece",
    calories: 100,
    protein: 2,
    carbs: 11,
    fat: 6,
  },
  {
    name: "Chutney Powder (podi)",
    unit: "per_10g",
    calories: 55,
    protein: 2,
    carbs: 4,
    fat: 3,
  },
  {
    name: "Coconut (fresh)",
    unit: "per_50g",
    calories: 177,
    protein: 1.8,
    carbs: 6.6,
    fat: 16.4,
  },
  {
    name: "Cucumber",
    unit: "per_100g",
    calories: 16,
    protein: 0.7,
    carbs: 3.6,
    fat: 0.1,
  },
  {
    name: "Tomato",
    unit: "per_100g",
    calories: 18,
    protein: 0.9,
    carbs: 3.9,
    fat: 0.2,
  },
  {
    name: "Onion",
    unit: "per_100g",
    calories: 40,
    protein: 1.1,
    carbs: 9.3,
    fat: 0.1,
  },
  {
    name: "Carrot",
    unit: "per_100g",
    calories: 41,
    protein: 0.9,
    carbs: 10,
    fat: 0.2,
  },
  {
    name: "Spinach (cooked)",
    unit: "per_100g",
    calories: 41,
    protein: 5.3,
    carbs: 3.6,
    fat: 0.5,
  },
  {
    name: "Broccoli (cooked)",
    unit: "per_100g",
    calories: 55,
    protein: 3.7,
    carbs: 11.2,
    fat: 0.6,
  },
  {
    name: "Sweet Corn (boiled)",
    unit: "per_100g",
    calories: 96,
    protein: 3.4,
    carbs: 21,
    fat: 1.5,
  },
  {
    name: "Sweet Potato (boiled)",
    unit: "per_100g",
    calories: 86,
    protein: 1.6,
    carbs: 20,
    fat: 0.1,
  },
  {
    name: "Rice Flour Dosa",
    unit: "per_100g",
    calories: 200,
    protein: 3,
    carbs: 39,
    fat: 3,
  },
  {
    name: "Wheat Dosa",
    unit: "per_100g",
    calories: 170,
    protein: 4,
    carbs: 30,
    fat: 3,
  },
  {
    name: "Keema (mutton)",
    unit: "per_100g",
    calories: 250,
    protein: 24,
    carbs: 0,
    fat: 17,
  },
  {
    name: "Keema (chicken)",
    unit: "per_100g",
    calories: 210,
    protein: 24,
    carbs: 0,
    fat: 12,
  },
];

async function main() {
  for (const f of FOODS) {
    await prisma.foodItem.upsert({
      where: { name: f.name },
      update: f,
      create: f,
    });
  }
  console.log("Seeded food items:", FOODS.length);
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(() => prisma.$disconnect());
